version: '3.4'

services:

  api:
    container_name: "api"
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: api/Dockerfile

  db:
    container_name: "db"
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - 'my-db:/var/opt/mssql'

  seq:
    container_name: "seq"
    image: datalust/seq:latest
    ports:
      - 5341:80
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - 'my-seq:/data'

# Names our volume
volumes:
  my-db:
  my-seq: